options {
    directory "/tmp";
    empty-zones-enable false;
};

zone "dummy.local" {
    type master;
    file "/etc/bind/dummy.zone";
};

// not sure what it does but my intent was to serve non-authoritative records,
// and it seems to work
zone "." {
    type redirect;
    file "/etc/bind/cache.db";
};
